// import { Geist, Geist_Mono } from "next/font/google";
// import { PlayfairDisplay } from "next/font/google";
import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
  variable: "--font-playfair",
  display: "swap",
});

const playfairItalic = Playfair_Display({
  subsets: ["latin"],
  weight: ["400"],
  style: "italic",
  variable: "--font-playfair-italic",
});

export const metadata = {
  title: "OrtoOgrodzińska",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${playfair.variable} ${playfairItalic.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
